import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import JSZip from 'jszip';
import { extractXmind } from '../src/lib/documents/extract-xmind.ts';
import { renderDocumentPreview } from '../src/lib/documents/render-document-preview.ts';
import { chunkDocumentSections } from '../src/lib/documents/chunk-text.ts';

const base = new URL('../test-fixtures/scholarflow/06_mindmap_audio/', import.meta.url);
const archive = async (name, content) => new JSZip().file(name, content).generateAsync({ type: 'nodebuffer', compression: 'DEFLATE' });
const results = [];
for (const name of ['06_mindmap_hien_dai.xmind', '07_mindmap_legacy.xmind']) {
  const buffer = await readFile(new URL(name, base));
  const result = await extractXmind(buffer);
  assert.equal(result.pageCount, 2);
  assert.equal(result.sections.length, 12);
  for (const marker of ['SF-XM-OSPF-42', 'SF-XM-3NF-73', 'SF-XM-DETACHED-19', 'Tiếng Việt', 'Dijkstra']) assert.ok(result.text.includes(marker), marker);
  const chunks = chunkDocumentSections(result.sections);
  const chunk = chunks.find(c => c.content.includes('SF-XM-3NF-73'));
  assert.equal(chunk.pageNumber, 2);
  assert.match(chunk.sourceLabel, /Cơ sở dữ liệu > Ôn tập dữ liệu > Chuẩn hóa 3NF/);
  const preview = await renderDocumentPreview(buffer, 'XMIND', name, 2, chunk.content);
  assert.equal(preview.itemCount, 2);
  assert.ok(preview.html.includes('matched-preview'));
  assert.ok(preview.html.includes('mindmap-node'));
  assert.ok(preview.html.includes('mindmap-tree'));
  assert.ok(!preview.html.includes('<pre>'), 'XMind preview is a connected diagram, not text blocks');
  assert.ok(preview.html.includes('SF-XM-3NF-73'));
  assert.ok(!preview.html.includes('SF-XM-OSPF-42'));
  await assert.rejects(renderDocumentPreview(buffer, 'XMIND', name, 3), /không tồn tại/);
  results.push(result);
  const first = await renderDocumentPreview(buffer, 'XMIND', name, 1);
  assert.ok(first.html.includes('mindmap-detached-group'));
  assert.ok(first.html.includes('SF-XM-DETACHED-19'));
}
assert.deepEqual(results[0], results[1], 'JSON and legacy XML preserve identical text and branch paths');
await assert.rejects(extractXmind(await readFile(new URL('08_xmind_hong_KHONG_UPLOAD_THANH_CONG.xmind', base))), /thiếu content/);
await assert.rejects(extractXmind(Buffer.from('not a zip')), /file hỏng/);
await assert.rejects(extractXmind(await archive('content.json', '{')), /JSON/);
await assert.rejects(extractXmind(await archive('content.json', '[]')), /1 đến 200/);
await assert.rejects(extractXmind(await archive('content.json', JSON.stringify([{ rootTopic: {} }]))), /không hợp lệ/);
await assert.rejects(extractXmind(await archive('content.json', ' '.repeat(8 * 1024 * 1024 + 1))), /8 MB/);
await assert.rejects(extractXmind(await archive('content.xml', '<!DOCTYPE x [<!ENTITY y SYSTEM "file:///private">]><x/>')), /thực thể/);
let deep = { title: 'leaf' };
for (let i = 0; i < 66; i++) deep = { title: 'branch', children: { attached: [deep] } };
await assert.rejects(extractXmind(await archive('content.json', JSON.stringify([{ rootTopic: deep }]))), /64 cấp/);
const many = { title: 'root', children: { attached: Array.from({ length: 5001 }, () => ({ title: 'node' })) } };
await assert.rejects(extractXmind(await archive('content.json', JSON.stringify([{ rootTopic: many }]))), /5.000/);
const unsafe = await archive('content.json', JSON.stringify([{ title: '<script>alert(1)</script>', rootTopic: { title: '<img src=x onerror=alert(1)>', notes: { plain: { content: '<iframe src=file:///private>' } } } }]));
const safe = await renderDocumentPreview(unsafe, 'XMIND', '<script>title</script>');
assert.ok(!safe.html.includes('<script>'));
assert.ok(!safe.html.includes('<img src=x'));
assert.ok(safe.html.includes('&lt;iframe'));
const prefixed = '<x:xmap-content xmlns:x="urn:xmind:xmap:xmlns:content:2.0"><x:sheet><x:title>Sheet</x:title><x:topic><x:title>Tiếng Việt có dấu</x:title></x:topic></x:sheet></x:xmap-content>';
assert.match((await extractXmind(await archive('content.xml', prefixed))).text, /Tiếng Việt có dấu/);
console.log('PASS XMind: JSON/XML, 2 sheets, 12 nodes, notes, labels, detached, ancestry, chunk location, preview highlight, invalid inputs, zip expansion limits, XSS');
